# Generated by Django 4.1 on 2022-09-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('is_premium', models.BooleanField(default=False)),
                ('event_image', models.ImageField(upload_to='event.png')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
