# Generated by Django 4.1 on 2022-09-21 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
